### ISSUE TITLE
Add Soft Event parameters

### ISSUE THREAD

**Issue by RajSSS5** [CSCI-150-Lab2-Team13/Palmanac#14]
Need to determine Soft Event parameters to make schedule generation possible

**Comment by RajSSS5** [comment]
Priority/Time allocated (weekly/daily)/Start Date End Date/ Acceptable Days of the week/ Acceptable times

**Comment by RajSSS5** [comment]
It might be better to have the selected calendar render inside the add event form and only allow adding events from there

**Comment by RajSSS5** [comment]
Replacing schedule generator with drag/drop

**Comment by alemor10** [comment]
u suck rajBOI
